version: '2'
services:
  tomcat-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
    - /usr/local/tomcat/conf/

  tomcat-server:
    ports:
      - ${http_port}:8080/tcp
    labels:
      io.rancher.scheduler.global: 'true'
    tty: true
    image: tomcat:8.0.53
    stdin_open: true
    volumes_from:
      - tomcat-data