# Php & Apache
web:
  image: php:7.1.1-apache
  hostname: ${web_hostname}/
  domainname: ${web_hostname}
  tty: true
  labels:
    se.andreklang.discover.domainname: ${web_hostname}
  links:
    - mysql:mysql
  volumes:
    - /home/docker/${STACK_NAME}/html:/var/www/html
  environment:
    MYSQL_HOST: mysql
    MYSQL_DATABASE: ${sql_db}
    MYSQL_PASSWORD: ${sql_pass}

# MySql
mysql:
  image: mysql
  volumes:
    - /home/docker/${STACK_NAME}/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${sql_pass}
    MYSQL_DATABASE: ${sql_db}