.catalog:
  name: "Lamp Stack"
  version: "v7.1"
  description: "Linux Apache MySql Php"
  minimum_rancher_version: v0.56.0
  maintainer: "Christian Bartrina <christianbartrina@gmail.com"
  uuid: lamp-0
  questions:

    - variable: "STACK_NAME"
      description: "Has to be exactly as the stack's name (see issue #3393)"
      label: "Stack Name:"
      required: true
      default: "lamp"
      type: "string"

    - variable: "web_hostname"
      description: "Web hostname"
      label: "Hostname:"
      required: true
      default: "myproject.andreklang.se"
      type: "string"

    - variable: "sql_db"
      description: "Database name"
      label: "Mysql database:"
      required: true
      default: "project_db"
      type: "string"

    - variable: "sql_pass"
      description: "Database pass"
      label: "Mysql pass:"
      required: true
      default: "SomethingSecretThatIsHardToGuess"
      type: "string"

web:
  scale: 1
  retain_ip: true

mysql:
  scale: 1
  retain_ip: true